export const DEFAULT_PROFILE_ICON = 'i-lucide-user'

export const PROFILE_ICONS = [
  { label: 'Usuario', icon: 'i-lucide-user' },
  { label: 'Empresa', icon: 'i-lucide-briefcase' },
  { label: 'Tienda', icon: 'i-lucide-store' },
  { label: 'Casa', icon: 'i-lucide-home' },
  { label: 'Idea', icon: 'i-lucide-lightbulb' },
  { label: 'Cafe', icon: 'i-lucide-coffee' },
  { label: 'Corazon', icon: 'i-lucide-heart' },
  { label: 'Rayo', icon: 'i-lucide-zap' },
  { label: 'Hoja', icon: 'i-lucide-leaf' },
  { label: 'Estrella', icon: 'i-lucide-star' },
  { label: 'Carro', icon: 'i-lucide-car' },
  { label: 'Camion', icon: 'i-lucide-truck' },
  { label: 'Bicicleta', icon: 'i-lucide-bike' },
  { label: 'Calculadora', icon: 'i-lucide-calculator' },
  { label: 'Notas', icon: 'i-lucide-notebook' },
  { label: 'Lista', icon: 'i-lucide-clipboard-list' },
  { label: 'Caja', icon: 'i-lucide-package' },
  { label: 'Carrito', icon: 'i-lucide-shopping-cart' },
  { label: 'Etiqueta', icon: 'i-lucide-tag' },
  { label: 'Billetera', icon: 'i-lucide-wallet' },
  { label: 'Billete', icon: 'i-lucide-banknote' },
  { label: 'Grafica', icon: 'i-lucide-line-chart' },
  { label: 'Barras', icon: 'i-lucide-bar-chart-3' },
  { label: 'Pastel', icon: 'i-lucide-pie-chart' },
  { label: 'Fabrica', icon: 'i-lucide-factory' },
  { label: 'Herramienta', icon: 'i-lucide-wrench' },
  { label: 'Martillo', icon: 'i-lucide-hammer' },
  { label: 'Campana', icon: 'i-lucide-bell' },
  { label: 'Calendario', icon: 'i-lucide-calendar' },
  { label: 'Pata', icon: 'i-lucide-paw-print' }
]
